// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Badge: typeof import("./src/lib/components/ui/badge/badge.svelte")["default"]
    const Button: typeof import("./src/lib/components/ui/button/button.svelte")["default"]
    const Card: typeof import("./src/lib/components/ui/card/card.svelte")["default"]
    const Cardaction: typeof import("./src/lib/components/ui/card/card-action.svelte")["default"]
    const Cardcontent: typeof import("./src/lib/components/ui/card/card-content.svelte")["default"]
    const Carddescription: typeof import("./src/lib/components/ui/card/card-description.svelte")["default"]
    const Cardfooter: typeof import("./src/lib/components/ui/card/card-footer.svelte")["default"]
    const Cardheader: typeof import("./src/lib/components/ui/card/card-header.svelte")["default"]
    const Cardtitle: typeof import("./src/lib/components/ui/card/card-title.svelte")["default"]
    const PageNav: typeof import("./src/lib/components/PageNav.svelte")["default"]
    const PdfViewer: typeof import("./src/lib/components/PdfViewer.svelte")["default"]
    const Popover: typeof import("./src/lib/components/ui/popover/popover.svelte")["default"]
    const Popoverclose: typeof import("./src/lib/components/ui/popover/popover-close.svelte")["default"]
    const Popovercontent: typeof import("./src/lib/components/ui/popover/popover-content.svelte")["default"]
    const Popoverportal: typeof import("./src/lib/components/ui/popover/popover-portal.svelte")["default"]
    const Popovertrigger: typeof import("./src/lib/components/ui/popover/popover-trigger.svelte")["default"]
    const Sidebar: typeof import("./src/lib/components/blocks/Sidebar.svelte")["default"]
    const TopBar: typeof import("./src/lib/components/blocks/TopBar.svelte")["default"]
}

export {}
